# Use Python base image
FROM python:3.9

# Set working directory
WORKDIR /app

# Copy files and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the rest of the code
COPY . .

# Expose backend port
EXPOSE 5000

# Run Flask app
CMD ["python", "app.py"]
